### ISSUE TITLE
Animation with human mesh?

### ISSUE THREAD

**Issue by forresti** [alvinliu0/HA2G#6]
This is really great work! I got train_feature_extractor_expressive.py to run, and it produced the following video: 

https://user-images.githubusercontent.com/2020010/199653034-6d4dcf21-65dc-425f-b813-7612f0490f7d.mp4

It looks good, but the human motion is using a line-based skeleton:
![line drawing](https://user-images.githubusercontent.com/2020010/199653168-9e3b36cb-7d4a-46f9-9941-8b3276d0d702.png)

I'd like to show an animation on a human mesh, like the following screenshot from your [demo video](https://www.youtube.com/watch?v=CG632W-nIWk):
![mesh](https://user-images.githubusercontent.com/2020010/199653293-948ba134-4979-47f2-ad96-3841289c4c59.png)

I was wondering, for your demo video, what software did you use to render it as an "animated mesh" instead of an "animated line drawing?"

**Comment by QianyiWu** [comment]
Hi @forresti 

Thanks for your interest in our work! The human animation is created by Blender. We take inspiration from [here](https://github.com/ai4r/Gesture-Generation-from-Trimodal-Context/tree/master/blender) to convert the motion of different joints into animation.

**Comment by ZZQ00100** [comment]
Hello, the video I rendered after running the code looks like this, and I know this is not normal. I would like to ask, how do you render a normal skeleton video?
![Snipaste_2024-07-11_21-07-36](https://github.com/alvinliu0/HA2G/assets/92974363/ec3bf061-dd9b-4230-8685-05f5f4f3f675)
