### ISSUE TITLE
quantitative results in the paper

### ISSUE THREAD

**Issue by zyhbili** [alvinliu0/HA2G#8]
In the repo, it seems evaluate on the val dataset as in ted_gesture_original.log the best fgd is 3.072, and i didn't find the code to evaluate on the test dataset.
I wonder you report which dataset's results (val or test) in the paper ?

**Comment by alvinliu0** [comment]
Hi:

We follow the evaluation protocol provided in Trimodal (https://github.com/ai4r/Gesture-Generation-from-Trimodal-Context/blob/master/scripts/train.py#L476) and set the val set as testset. In practice, we find that the val and test set follows the similar distribution without much domain gap. Hence we report results following them. For fair comparison, the results could be re-evaluated on the test set for all baselines.
